### ISSUE TITLE
UIKit Consistency error

### ISSUE THREAD

**Issue by PaulAchess** [molinch/FFImageLoading#113]
Hi!

I'm using FFImageLoading in a Xamarin Forms project, and I reproduce all the time the exception:
```
UIKit.UIKitThreadAccessException: UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread
```

When calling 
```
await cachedImage.GetImageAsPNG(100);
```

On the renderer here: https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Forms.Touch/CachedImageRenderer.cs#L309

It seems the operation `image.ResizeUIImage(…)` can only be done in the UI Thread.

I'm wondering if `Task.Run(…)` should be replaced with something specifically for the UI Thread? Or if I had to invoke it on the main thread myself?

Thanks for your library!

**Comment by daniel-luberda** [comment]
Yes, it should be easy to fix - I'll try to fix that. Meanwhile you can fix that using this method inside 
```
Device.BeginInvokeOnUIThread(() => {});
```

**Comment by PaulAchess** [comment]
Actually I tried this and it does not work, could `Task.Run()` bypass it?

Do you need help fixing it? A `TaskCompletionSource` + `InvokeOnMainThread(() => {})` should be enough I think.

**Comment by daniel-luberda** [comment]
Yes. Do you have a stack trace? I have to know what exact line needs to be called on UI thread.

**Comment by PaulAchess** [comment]
I can't seem to get a proper stacktrace (more than `GetImageAsByte`), probably because it is threaded.

However when I look at the code, I think it is on `image.AsPNG()` (and probably ` image.AsJPEG()` as well) (https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Forms.Touch/CachedImageRenderer.cs#L320)

I'm not using desiredWidth or desiredHeight, but I also think `image.ResizeUIImage()` part of UIKit too.

Do you have any idea how to get a better stacktrace? Maybe using a .NET Reflector?

**Comment by daniel-luberda** [comment]
Done :)

**Comment by PaulAchess** [comment]
#Efficiency

Thanks :)

**Comment by PaulAchess** [comment]
Watch out I think `image.AsPng()` ([here](https://github.com/molinch/FFImageLoading/commit/0014f29464361630008d96058de49521ddcbc038#diff-5b121fd67bb4107a3b7dcfee2ec4b306R322)) also needs it

**Comment by daniel-luberda** [comment]
It should be fine :)

https://developer.xamarin.com/api/member/MonoTouch.UIKit.UIImage.AsJPEG()/

> Remarks: This can be used from a background thread.

**Comment by PaulAchess** [comment]
Then I don't understand why it was crashing for me. 
I was not using desiredWidth nor desiredHeight, which means `ResizeImage` should not have been called.

Could `imageData.ToArray()` be unsafe for background threads?

**Comment by daniel-luberda** [comment]
That's strange - all other methods shouldn't require UI thread. Does it still crash after fixing?

**Comment by PaulAchess** [comment]
The fix I tried was a lot less subtle (surround everything) and now I tried yours.

Believe it or not, it crashes at the very beginning, with `Control.Image` ([here](https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Forms.Touch/CachedImageRenderer.cs#L310))

**Comment by PaulAchess** [comment]
I decompiled the assembly, there is a dirty `UIApplication.EnsureUIThread()` on the getter (and the setter, good to know) of UIImageView.Image.

Stupid fat hobbit.

**Comment by daniel-luberda** [comment]
Thanks for debugging. Fixed it once again (didn't have opportunity to test it). This should fix it: 

https://github.com/molinch/FFImageLoading/commit/635f373769f79172be4f504ea197238163a6f13a

**Comment by PaulAchess** [comment]
Just tested it, works like a charm. Also I checked, you can remove it from ResizeUIImage, it is not needed.

Thanks for the fix! I still cannot believe it was coming from a getter, that is so sneaky of them.

**Comment by daniel-luberda** [comment]
Changed it - thanks for your help.

>  I still cannot believe it was coming from a getter, that is so sneaky of them.
I didn't expect that too!

**Comment by PaulAchess** [comment]
I checked, it is not needed to dispatch the `image.ResizeUIImage`, it can work on background.

You can remove it if you want.

**Comment by daniel-luberda** [comment]
It's removed already here: https://github.com/molinch/FFImageLoading/commit/dc75cbbef92887f7db3d5db5ae31caaa833f4ad1

**Comment by PaulAchess** [comment]
:+1:
